// demo/2023/todo-demo/src/App.vue
<!--
 * @Author: heywc “1842347744@qq.com”
 * @Date: 2023-03-24 15:17:19
 * @LastEditors: heywc “1842347744@qq.com”
 * @LastEditTime: 2023-04-03 15:47:54
 * @FilePath: /DailyLearning/demo/2023/todo-demo/src/App.vue
 * @Description: 这是默认设置,请设置`customMade`, 打开koroFileHeader查看配置 进行设置: https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE
-->
<template>
  <div id="app">
    <nav>
      <router-link to="/">Home</router-link> |
      <router-link to="/about">About</router-link>
      <router-link to="/VirtualList">VirtualList</router-link>
    </nav>
    <router-view/>
  </div>
</template>

<style lang="scss">
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  color: #2c3e50;
}

nav {
  padding: 30px;

  a {
    font-weight: bold;
    color: #2c3e50;

    &.router-link-exact-active {
      color: #42b983;
    }
  }
}
</style>

// demo/2023/virtualList/src/App.tsx
/*
 * @Author: heywc “1842347744@qq.com”
 * @Date: 2023-04-24 10:40:29
 * @LastEditors: heywc “1842347744@qq.com”
 * @LastEditTime: 2023-04-24 11:23:17
 * @FilePath: /DailyLearning/demo/2023/virtualList/src/App.tsx
 * @Description: 这是默认设置,请设置`customMade`, 打开koroFileHeader查看配置 进行设置: https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE
 */
import { useState, memo} from 'react'
import Virlist from './components/Virlist'
import './App.css'

function App() {
    const [count, setCount] = useState(0)
    const [items] = useState(Array(20000).fill(1));
    const ItemBox = memo(function({data='', index = 0, style={}}:any) {
        return (<div style={style} id ={`item-${index}`}>
            {data}
        </div>)
    })
    return (
        <>
            首页
            <Virlist list={items} containerHeight={500} ItemBox={ItemBox}></Virlist>
        </>
  )
}

export default App
